language: go
go:
  - 1.11.x
  - master
env:
  - GO111MODULE=on
script:
  - make ci
after_script:
  - goveralls -coverprofile=coverage.out
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      go: 1.11.x
      condition: $TRAVIS_OS_NAME = linux
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
