language: go
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
script:
  - make test
  - make cover
after_script:
  - goveralls -coverprofile=coverage.out
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
