language: go
matrix:
  include:
    - os: linux
      go: 1.8.x
    - os: osx
      go: 1.8.x
    - os: linux
      go: 1.9.x
    - os: osx
      go: 1.9.x
script:
  - make test
  - make cover
after_script:
  - goveralls -coverprofile=coverage.out
notifications:
  slack: linyows:2oeZ2qcLnaMjbnEYodwEXKTr
  email: false
